### ISSUE TITLE
Which homeassistant module are you using

### ISSUE THREAD

**Issue by polzy** [wonderslug/MMM-HomeAssistantDisplay#1]
Which homeassistant's module are you using   ?

I have this module : https://github.com/bruxy70/Garbage-Collection
but I can not configure it with MMM-HomeAssistantDisplay

Value | Meaning
-- | --
0 | Collection is today
1 | Collection is tomorrow
2 | Collection is later

i have try this : 

       title: "Poubelles",				
       useModuleTigger: false,
        moduleTriggerTemplate: `{{ states.sensor.carton.state == "0"}}`,
        moduleTriggerEntities: ["binary_sensor.carton"],
        class: "garbage_collection.collect_garbage",
        sections: [{
            triggerEntities: [
                "sensor.poubelle",
                "sensor.carton"
            ],
            displayTemplate: `
                {% if states.sensor.poubelle.state == "0" %}<i class='mdi mdi-trash-can'></i>{% endif %}
                {% if states.sensor.carton.state == "0" %}<i class='mdi mdi-recycle'></i>{% endif %}
                `,
            class: "put-outs"

**Comment by wonderslug** [comment]
Howdy, 

For me personally I am using the Google Calendar integration to get my local pickup schedule and then I setup a binary_sensor base on events.

For what your doing I would convert the states to integers and compare that way.

```
{% if states.sensor.poubelle.state|int == 0 %}<i class='mdi mdi-trash-can'></i>{% endif %}
{% if states.sensor.carton.state|int == 0 %}<i class='mdi mdi-recycle'></i>{% endif %}
```

Make sure you check your template in the [Home Assistant Template Editor](https://my.home-assistant.io/redirect/developer_template).  The module will display whatever the same output from that would be.  It uses the same template rendering function of HA.

**Comment by polzy** [comment]
thanks you so much,
it works


        title: "Poubelles",				
       useModuleTigger: false,
        moduleTriggerTemplate: `{{ states.sensor.carton.state == "1"}}`,
        moduleTriggerEntities: ["garbage_collection.collect_garbage"],
        class: "garbage_collection.collect_garbage",
        sections: [{
            triggerEntities: [
                "sensor.poubelle",
                "sensor.carton"
            ],
            displayTemplate: `
                {% if states.sensor.poubelle.state == "1" %}{%- set icon = "bell-ring blink" -%}<i class='mdi mdi-trash-can'</i> <i class='mdi mdi-{{icon}}'></i> - Demain{% endif %}
                
                {% if states.sensor.carton.state == "1" %}{%- set icon = "bell-ring blink" -%}<i class='mdi mdi-trash-can'</i> <i class='mdi mdi-{{icon}}'></i> - Demain{% endif %}
                `,
            class: "put-outs"
        }]
    },

**Comment by wonderslug** [comment]
Glad to hear it.
