### ISSUE TITLE
HA sensor state not refreshing on MM module

### ISSUE THREAD

**Issue by uros76** [wonderslug/MMM-HomeAssistantDisplay#17]
Hi. Thanks for a great module :). 

I can see the HA sensor state displayed correctly but if the state changes this does not get updated on my MM. 
After I restart the MM the correct state shows up. 
Am I missing something or doing it wrong? 🤷‍♂️

Here is my module code in the MM config:  
```
{
    module: 'MMM-HomeAssistantDisplay',
    position: 'bottom_center',
    config: {
        host: "192.168.1.226",
        token: "hidden",
        port: 8123,
        title: "HA inputs",
        sections: [{
            triggerEntities: [
                "states.lock.front_door_2.state"
            ],
                displayTemplate: `
                {%- if states.lock.front_door_2.state == "locked" -%}
                {%- set icon = "home-lock" -%}
                {%- set stateText = "Locked" -%}
                {%- elif states.lock.front_door_2.state == "unlocked" -%}
                {%- set icon = "home-lock-open" -%}
                {%- set stateText = "Unlocked" -%}
                {%- endif -%}
                <i class='mdi mdi-{{icon}}'></i> Front door - {{stateText}}
                `,
        }]
    },
},
```

**Comment by wonderslug** [comment]
Hey. glad you like.

you have the trigger entity as "states.lock.front_door_2.state"
 should just be **lock.front_door_2**

**Comment by uros76** [comment]
Oh boy, now I am ashamed of this tiny mistake 😒. It works of course, thanks a lot! 👍😊

**Comment by wonderslug** [comment]
No problem. Easy mistake to make.

**Comment by wonderslug** [comment]
So the display template is fully rendered by Home Assistant itself.  Im not sure whats going on with the last updated but you can check your displayTemplate using the Developer Tools Template renderer.  You should be able to see exactly what the output of the display template is going to be.

[![Open your Home Assistant instance and show your template developer tools.](https://my.home-assistant.io/badges/developer_template.svg)](https://my.home-assistant.io/redirect/developer_template/)

**Comment by uros76** [comment]
> So the display template is fully rendered by Home Assistant itself. Im not sure whats going on with the last updated but you can check your displayTemplate using the Developer Tools Template renderer. You should be able to see exactly what the output of the display template is going to be.
> 
> [![Open your Home Assistant instance and show your template developer tools.](https://camo.githubusercontent.com/47f3a8b580f1573997e8cd51002e17ac8fa3bf69eab78153eadc466fc9604ff0/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f646576656c6f7065725f74656d706c6174652e737667)](https://my.home-assistant.io/redirect/developer_template/)

Tried it and the relative time works correctly, it gets updated in the output. The icon doesn't get processed but that's normal for an alphanumerical renderer. 
![image](https://github.com/wonderslug/MMM-HomeAssistantDisplay/assets/25409772/1ae31fbb-d6ae-43c3-8c11-9335f5d96a4c)

**Comment by uros76** [comment]
I might end up just using the fixed time of the last update state. Relative processed time somehow doesn't work 🤷‍♂️.
