### ISSUE TITLE
Wrong examples Can you please update

### ISSUE THREAD

**Issue by thundergreen** [wonderslug/MMM-HomeAssistantDisplay#2]
Hello I added exactly your examples but it is like some commas or sign are missing and i cannot firgure it out. Can you please recheck  you example for the windows sensors as it does not work. Behind the port there must also be a comma for example. But a ai am not familiar with the json I freak out here :P

**Comment by holdestmade** [comment]
```
let perimeterWindowSections = [];
perimeterWindows.forEach((item, i) => {
    perimeterWindowSections.push({
        triggerEntities: [
            item.entity
        ],
        displayTemplate: `
        {% if states.${item.entity}.state == "on" %}<i class='mdi mdi-window-open'></i> ${item.name}{% endif %}
        `,
        class: "window"
	})
})
```
