### ISSUE TITLE
Loosing connection, no updates after certain time

### ISSUE THREAD

**Issue by Mugga6315** [wonderslug/MMM-HomeAssistantDisplay#21]
I've got the issue that after sometime the homeassistant entities are not updating anymore. I've looked into the logs but couldn't find any log entry. I just suddelny stops receiving updates.

Any clue how I can debug this?

**Comment by rjfendricks** [comment]
I have a bit of information to add, but no real solutions.

For my setup, I have the MMM server running on a local computer and the client running on my Magic Mirror. After a few hours, I also notice that the homeassistant entities stop updating. However, if I connect to the MMM Server's IP address/port through a web browser from a third device, the client on the magic mirror magically recovers.

I still don't know all of the details, but I think that [MMM-HomeAssistantDisplay.js](https://github.com/wonderslug/MMM-HomeAssistantDisplay/blob/main/MMM-HomeAssistantDisplay.js) runs as an instance on the client(s) while [node_helper.js](https://github.com/wonderslug/MMM-HomeAssistantDisplay/blob/main/node_helper.js) runs on the server. My theory is that by connecting a new `MMM-HomesassistantDisplay` instance, the `node_helper` script is being forced to reconnect back to Home Assistant and gets everything moving again. 

Looking further into it, when I observe the logs I see that the statement [here](https://github.com/wonderslug/MMM-HomeAssistantDisplay/blob/6a67a6160f55dfab531c8164959dcb0a52606eb8/node_helper.js#L200C52-L200C52) stops printing when the issue manifests. Tracing it backwards in the code, my best guess is that the `state_changed` event is no longer getting fired from the `HassWs` object (which is bound [here](https://github.com/wonderslug/MMM-HomeAssistantDisplay/blob/6a67a6160f55dfab531c8164959dcb0a52606eb8/node_helper.js#L164C6-L164C6)).

I have no clue yet why this stops firing events or why connecting a new instance to the MMM server seems to fix this. If I have time/motivation later I'll continue to look into it, but with any luck someone more versed in this architecture than me can make more sense of my findings :)

**Comment by rjfendricks** [comment]
After looking into it some more, it probably has something to do with this [3rd party Node module](https://github.com/filp/homeassistant-ws/tree/master). Either it isn't being configured correctly or there's a bug in the linked module, but at this point I don't have enough expertise/motivation to figure it out.

Instead, I'll propose a hacky workaround, which I pushed up as PR #22. It's definitely not solving the issue at hand, but it will at least make the module functional until someone fixes it properly. Plus, I can think of at least 1 legitimate  use case that might make this helpful regardless.

**Comment by wonderslug** [comment]
should be closed by PR #22
