### ISSUE TITLE
Cannot find working Configuration for Usecase

### ISSUE THREAD

**Issue by urkman5000** [wonderslug/MMM-HomeAssistantDisplay#23]
Firstly im sorry cause im very new to this json code thing. Got a few modlues up and running but having a hard time setting up this.
My Goal is just to show the Battery Status of a specific Remote entity. Played around alot with the module Configuration but cannot find a working module config for this. Could you proboably provide me something working? The Remote battery status i wanna display is from an ikea tradfri remote (z2m) if that matters.

**Comment by urkman5000** [comment]
This is my current config dunno where i gone wrong
Any help appreciated.

{
    module: 'MMM-HomeAssistantDisplay',
    position: 'bottom_left',
    config: {
        host: "YOUR_HOME_ASSISTANT_HOST",
        token: "YOUR_HOME_ASSISTANT_TOKEN",
        port: 8123,
        useTLS: true,
        title: "Batteriestatus",                
        useModuleTrigger: true,
        moduleTriggerTemplate: `{{ states.sensor.your_battery_entity.state }}`,
        moduleTriggerEntities: ["sensor.sensor.your_battery_entity.state"],
        class: "batterie-status",
        sections: [{
            triggerEntities: [
                "sensor.sensor.your_battery_entity.state"
            ],
            displayTemplate: `
                <i class='mdi mdi-battery'></i> Batteriestatus: {{ states.sensor.your_battery_entity.state }}
                `,
            class: "battery-section"
        }]
    }
},

**Comment by wonderslug** [comment]
Hey,  one issue may be your moduleTriggerEntities.

Currently you have 

```
moduleTriggerEntities: ["sensor.sensor.your_battery_entity.state"]
```

probably should be 
```
moduleTriggerEntities: ["sensor.your_battery_entity"]
```


your tiggerEntities also should probably only be.

```
triggerEntities: [
"sensor.your_battery_entity"
],
```

**Comment by wonderslug** [comment]
Since there has been no response in months. im closing this.  Reopen if there is still an issue
