### ISSUE TITLE
Error in documentation, code for Simple example

### ISSUE THREAD

**Issue by PieBa** [wonderslug/MMM-HomeAssistantDisplay#24]
For some years I have a Magic Mirror and now I moved from FHEM to Home Assistant.
So I needed a way to get the data from Home Assistant instead of FHEM.

I found your module and I like it.
Unfortunately, I started trying the code of your simple example.
It didn't work at once and it took me some time to find out, there are two small errors in the example code:
- after `token: "..."` a comma is missing
- at the end of `displayTemplate: ` the closing backtick is missing.

Maybe this helps some other newbies like me

**Comment by wonderslug** [comment]
Fixed, thanks
