### ISSUE TITLE
errors in config

### ISSUE THREAD

**Issue by 1969selwyn** [wonderslug/MMM-HomeAssistantDisplay#3]
Hello,
I'm very interested to install your Module.
I tried to install the part for open windows, but I keep on getting errors when booting Magic Mirror.
Can you please check the example code provided?
The part of code for on top of config.js, does that have to be copied above or below:
var config = {
	address: "localhost", 
When checking the code, for the part to be copied on top of config.js,  counting the brackets, at least }) are missing to stay in line with the opening brackets.
Also on 2 places ; are used. Shouldn't that be komma's?
For the module entry, after port: 8123 the , is missing.
I played around with all these variables but didn't get it working.
In the documentation, could you also add the required settings for Home Assistant to ensure on both ends it works as expected?
I appreciate your support,
Thanks for looking into the issue.

**Comment by holdestmade** [comment]
Got this working. Add a comma after port and this is working:

```
let perimeterWindowSections = [];
perimeterWindows.forEach((item, i) => {
    perimeterWindowSections.push({
        triggerEntities: [
            item.entity
        ],
        displayTemplate: `
        {% if states.${item.entity}.state == "on" %}<i class='mdi mdi-window-open'></i> ${item.name}{% endif %}
        `,
        class: "window"
	})
})
```
