### ISSUE TITLE
Possibility to make service calls within Module?

### ISSUE THREAD

**Issue by jlafuenti** [wonderslug/MMM-HomeAssistantDisplay#34]
I am trying to pull a shopping list from Home Assistant into Magic Mirror.  However the list features inside Home Assistant don't store the entries in the state, and as such can't be pulled from the module, any text entity has a character limit of 255 which a shopping list can easily exceed.  Is it possible to have MagicMirror make the service call directly to get the full list which could then be displayed?

**Comment by wonderslug** [comment]
Not at this point.   The Home Assistant REST API does not have a way to run a service call remotely.   There is a WebSocket way but at this point it would be very difficult to work into a MagicMirror plugin.
