### ISSUE TITLE
Error: Cannot find module 'backoff'`

### ISSUE THREAD

**Issue by rafaelmathieu** [wonderslug/MMM-HomeAssistantDisplay#8]
I am getting this error:
`WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'backoff'`

Any idea how to fix it?

**Comment by wonderslug** [comment]
Should be there if you have done the ```npm install``` within the modules/MMM-HomeAssistantDisplay directory.

**Comment by rafaelmathieu** [comment]
Well I can't believe I didn't do it, that was it. Thanks for the quick reply. 

Sorry for the stupid issue.

> Should be there if you have done the `npm install` within the modules/MMM-HomeAssistantDisplay directory.

**Comment by wonderslug** [comment]
Np.  Glad you got it worked out.
